# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    delivery_addresses: ['a.ivanov@aladdin-rd.ru']
#    disable_delivery: true